CREATE TABLE servicesale (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(128),
description VARCHAR(128),
risk VARCHAR(128),
pic BLOB(1000000),
links VARCHAR(128),
price FLOAT,
tel VARCHAR(128));

CREATE TABLE account (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
balance FLOAT);




CREATE TABLE seller (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
username VARCHAR(128),
password VARCHAR(128),
nome VARCHAR(128),
cognome VARCHAR(128),
address VARCHAR(128),
mail VARCHAR(128),
account INTEGER,
FOREIGN KEY (account) REFERENCES account(id),
tel VARCHAR(128));


CREATE TABLE client (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
username VARCHAR(128),
password VARCHAR(128),
nome VARCHAR(128),
cognome VARCHAR(128),
address VARCHAR(128),
mail VARCHAR(128),
account INTEGER,
FOREIGN KEY (account) REFERENCES account(id),
tel VARCHAR(128));

CREATE TABLE servicesale_seller (
servicesale_id INTEGER,
seller_id INTEGER,
PRIMARY KEY (servicesale_id, seller_id),
FOREIGN KEY (servicesale_id) REFERENCES servicesale(id),
FOREIGN KEY (seller_id) REFERENCES seller(id)
);

CREATE TABLE servicesale_client (
servicesale_id INTEGER,
client_id INTEGER,
PRIMARY KEY (servicesale_id, client_id),
FOREIGN KEY (servicesale_id) REFERENCES servicesale(id),
FOREIGN KEY (client_id) REFERENCES client(id)
);